name: LLM Harness Evaluation

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-llm-nightly-test-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

# Controls when the action will run.
on:
  schedule:
    - cron: "30 12 * * *" # GMT time, 12:30 GMT == 20:30 China
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/llm-harness-evaluation.yml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model names, separated by comma and must be quoted.'
        required: true
        type: string
      precision:
        description: 'Precisions, separated by comma and must be quoted.'
        required: true
        type: string
      task:
        description: 'Tasks, separated by comma and must be quoted.'
        required: true
        type: string
      runs-on:
        description: 'Labels to filter the runners, separated by comma and must be quoted.'
        default: "accuracy"
        required: false
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-harness-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: temp-txt
      - name: verify file content
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: |
          ls cache
          cat cache/temp-txt
      - name: create temp.txt
        shell: bash
        run: |
          touch temp.txt
          echo "hello" >> temp.txt
     
      - name: Cache HTML and CSV
        uses: actions/cache/save@v3
        with:
          path: |
            ./*.txt
          key: temp-txt
